### ISSUE TITLE
Create documentation

### ISSUE THREAD

**Issue by Galexrt** [Galexrt/docker-zulip#11]
## ToDo:
- [x] How to use the image with docker-compose
- [x] How to use the container without docker-compose (Create scripts for an easy start)
- [x] Add a list of all env vars
- [x] Add explanation for all env vars
- [x] Add new env vars to wiki

**Comment by Galexrt** [comment]
Wiki entry has been added. https://github.com/Galexrt/docker-zulip/wiki

**Comment by Galexrt** [comment]
Script added in scripts/docker_start.sh

**Comment by Galexrt** [comment]
Updated the wiki pages.
